"""Lista de troféus do jogo base no PS5, em PT-BR e inglês."""
from __future__ import annotations


def _t(
    trophy_id: str,
    pt: str,
    en: str,
    description: str,
    tier: str = "bronze",
    category: str = "geral",
    missable: bool = False,
) -> dict:
    return {
        "id": trophy_id,
        "pt": pt,
        "en": en,
        "description": description,
        "tier": tier,
        "category": category,
        "missable": missable,
    }


TROPHIES = [
    _t("platinum", "O limite das possibilidades", "The Limits of the Possible", "Colete todos os troféus.", "platina", "platina"),
    _t("lilac_gooseberries", "Lilás e groselha", "Lilac and Gooseberries", "Encontre Yennefer de Vengerberg.", category="história"),
    _t("friend_in_need", "Amigo é para essas coisas", "A Friend in Need", "Encontre e liberte Dandelion.", category="história"),
    _t("necromancer", "Necromante", "Necromancer", "Ajude Yennefer a extrair informações do corpo de Skjall.", category="história"),
    _t("family_counselor", "Terapeuta da família", "Family Counselor", "Encontre a esposa e a filha do barão.", category="história"),
    _t("something_more", "Algo mais", "Something More", "Encontre Ciri.", category="história"),
    _t("xenonaut", "Marionete", "Xenonaut", "Visite Tir ná Lia e convença Ge'els a trair Eredin.", category="história"),
    _t("king_is_dead", "O rei está morto", "The King is Dead", "Derrote Eredin.", "prata", "história"),
    _t("passed_trial", "Passou no Teste", "Passed the Trial", "Conclua o jogo em qualquer dificuldade.", category="dificuldade"),
    _t("ran_gauntlet", "Superou o Desafio", "Ran the Gauntlet", "Conclua o jogo em Sangue e Glória ou Marcha da Morte.", "prata", "dificuldade"),
    _t("walked_path", "Seguiu o Caminho", "Walked the Path", "Conclua o jogo na dificuldade Marcha da Morte sem reduzi-la durante a campanha.", "ouro", "dificuldade", True),
    _t("professional", "Geralt: bruxo profissional", "Geralt: The Professional", "Conclua todos os contratos de bruxo do jogo base.", category="contratos"),
    _t("kingmaker", "Realeza", "Kingmaker", "Conclua a trama da escolha do monarca de Skellige.", category="missões", missable=True),
    _t("assassin_kings", "Regicida", "Assassin of Kings", "Participe do assassinato do rei Radovid.", category="missões", missable=True),
    _t("friends_benefits", "Amizade colorida", "Friends With Benefits", "Conclua a trama secundária de Keira Metz.", category="missões", missable=True),
    _t("full_crew", "Rapaziada", "Full Crew", "Traga todos os aliados exigidos para a batalha em Kaer Morhen.", category="missões", missable=True),
    _t("dendrologist", "Dendrólogo", "Dendrologist", "Adquira todas as habilidades de uma árvore.", category="progressão"),
    _t("enemy_enemy", "O inimigo do meu inimigo", "The Enemy of My Enemy", "Use Axii para fazer um adversário matar outro vinte vezes.", category="combate"),
    _t("humpty_dumpty", "Sai de baixo", "Humpty Dumpty", "Derrube dez adversários de lugares altos com Aard.", category="combate"),
    _t("environmental", "Complô contra a natureza", "Environmentally Unfriendly", "Mate cinquenta adversários usando o ambiente.", category="combate"),
    _t("kaer_morhen_trained", "Treinado em Kaer Morhen", "Kaer Morhen Trained", "Faça dez contra-ataques seguidos sem ser atingido nem bloquear.", category="combate"),
    _t("cant_touch", "Elegância", "Can't Touch This!", "Mate cinco adversários sem sofrer dano e sem usar Quen.", category="combate"),
    _t("evilest_thing", "Maldade pouca é bobagem...", "That Is the Evilest Thing...", "Incendeie o gás de Sonho do Dragão com um adversário em chamas dez vezes.", category="combate"),
    _t("mutant", "Mutante", "Mutant", "Preencha todos os espaços de mutagênicos.", category="progressão"),
    _t("butcher", "O carniceiro de Blaviken", "Butcher of Blaviken", "Mate pelo menos cinco adversários em menos de dez segundos.", "prata", "combate"),
    _t("triple_threat", "Ameaça tripla", "Triple Threat", "Mate três adversários em uma luta usando três métodos diferentes.", category="combate"),
    _t("brawler", "Encrenqueiro", "Brawler", "Derrote Olaf, o campeão de luta de Skellige.", "prata", "atividades"),
    _t("overkill", "Exagero", "Overkill", "Cause sangramento, envenenamento e queimadura no mesmo adversário dez vezes.", "prata", "combate"),
    _t("master_marksman", "Atirador de elite", "Master Marksman", "Mate cinquenta humanoides com tiros de besta na cabeça.", category="combate"),
    _t("what_was_that", "Pode isso, Arnaldo?", "What Was That?", "Ataque, contra-ataque, lance um Sinal e jogue uma bomba em menos de quatro segundos.", category="combate"),
    _t("even_odds", "O que é justo, é justo", "Even Odds", "Mate dois alvos de contrato sem Sinais, poções, mutagênicos, óleos ou bombas.", "prata", "contratos", True),
    _t("globetrotter", "Andarilho", "Globetrotter", "Descubra cem pontos de viagem rápida.", category="exploração"),
    _t("pest_control", "Dedetização", "Pest Control", "Destrua todos os ninhos de monstros em Velen e Novigrad ou em Skellige.", "prata", "exploração"),
    _t("card_collector", "Colecionador de cartas", "Card Collector", "Adquira todas as cartas de Gwent do jogo base.", category="gwent", missable=True),
    _t("gwent_master", "Mestre do gwent", "Gwent Master", "Derrote Tybalt e vença o torneio de Gwent no Passiflora.", category="gwent", missable=True),
    _t("lets_cook", "Vamos Cozinhar!", "Let's Cook!", "Aprenda doze fórmulas de poções.", category="alquimia"),
    _t("bombardier", "Carga explosiva", "Bombardier", "Adquira fórmulas de seis tipos diferentes de bomba.", category="alquimia"),
    _t("bookworm", "Rato de biblioteca", "Bookworm", "Leia trinta livros, diários ou documentos.", category="exploração"),
    _t("armed_dangerous", "Armado e perigoso", "Armed and Dangerous", "Encontre e equipe todas as peças de um conjunto de bruxo.", "prata", "equipamento"),
    _t("power_overwhelming", "Poder para dar e vender", "Power Overwhelming", "Mantenha ativos ao mesmo tempo os bônus dos cinco tipos de Local de Poder.", category="exploração"),
    _t("brawl_master", "Encrenqueiro de primeira", "Brawl Master", "Conclua as sequências de luta de Velen, Novigrad e Skellige.", category="atividades", missable=True),
    _t("fast_furious", "A todo gás", "Fast and Furious", "Vença todas as corridas de cavalo do jogo base.", category="atividades", missable=True),
    _t("munchkin", "Que gracinha!", "Munchkin", "Atinja o nível 35.", "ouro", "progressão"),
    _t("fire_hole", "Bomba, bomba, olha a bomba!", "Fire in the Hole", "Destrua dez ninhos de monstros usando bombas.", category="exploração"),
    _t("south_star", "Na raça", "Fist of the South Star", "Vença uma luta sem sofrer dano.", category="atividades", missable=True),
    _t("geralt_friends", "Geralt e Cia.", "Geralt and Friends", "Vença uma rodada de Gwent usando somente cartas neutras.", category="gwent"),
    _t("all_in", "Apostar tudo", "All In", "Use três cartas de herói em uma rodada de Gwent e vença a partida.", category="gwent"),
    _t("shrieker", "A plenos pulmões", "Shrieker", "Conclua o contrato do berrante.", category="contratos"),
    _t("vampire_slayer", "O caça-vampiros", "Fearless Vampire Slayer", "Conclua o contrato de Sarasti.", category="contratos"),
    _t("woodland_spirit", "Espírito do bosque", "Woodland Spirit", "Conclua o contrato do espírito do bosque pela solução que enfrenta o leshen.", category="contratos", missable=True),
    _t("fiend_foe", "Amizade dolorida", "Fiend or Foe?", "Conclua o contrato de Morvudd.", category="contratos"),
    _t("ashes", "Do pó ao pó", "Ashes to Ashes", "Conclua o contrato de Therazane.", category="contratos"),
    _t("doppler", "Dois é demais", "The Doppler Effect", "Conclua o contrato do dúplice de Novigrad.", category="contratos", missable=True),
]


assert len(TROPHIES) == 53


TROPHY_TIPS = {
    "platinum": "É liberado automaticamente quando os outros 52 troféus do jogo base estiverem concluídos.",
    "lilac_gooseberries": "Troféu automático da história. Continue o prólogo em Pomar Branco.",
    "friend_in_need": "Troféu automático da história. Conclua a busca principal por Dandelion em Novigrad.",
    "necromancer": "Troféu automático da história durante a investigação de Yennefer em Skellige.",
    "family_counselor": "Troféu automático da história ao encerrar a investigação da família do Barão Sanguinário.",
    "something_more": "Troféu automático da história ao encontrar Ciri.",
    "xenonaut": "Troféu automático da história no último ato.",
    "king_is_dead": "Troféu automático ao concluir a campanha e derrotar Eredin.",
    "passed_trial": "Termine a campanha. A Marcha da Morte também libera os troféus das dificuldades inferiores.",
    "ran_gauntlet": "Mantenha a Marcha da Morte até os créditos. Ele será liberado junto com Seguiu o Caminho.",
    "walked_path": "Comece na Marcha da Morte e nunca reduza a dificuldade. Confira a configuração depois do tutorial e preserve um save final.",
    "professional": "Conclua todos os contratos do jogo base. Leia os quadros de aviso, filtre o diário por contratos e ignore os contratos das expansões.",
    "kingmaker": "Conclua Possessão e O Senhor de Undvik, ajude Cerys ou Hjalmar em A Aposta do Rei e assista à Coroação.",
    "assassin_kings": "Feche a cadeia política de Roche e Dijkstra antes da Ilha das Brumas. Em Cegamente Óbvio, não use força contra Dijkstra.",
    "friends_benefits": "Conclua toda a trama de Keira. Na conversa final, mande-a para Kaer Morhen para também proteger Rapaziada.",
    "full_crew": "Garanta Keira, Triss, Roche, Ves, Zoltan, Ermion e Hjalmar antes da Ilha das Brumas.",
    "dendrologist": "Deixe para o fim. Faça um save, use uma Poção da Limpeza se necessário e compre toda uma árvore da versão Remastered até o troféu aparecer.",
    "enemy_enemy": "Use a ramificação de Axii que transforma um adversário em aliado. Faça vinte mortes controladas em grupos de inimigos fracos.",
    "humpty_dumpty": "Leve inimigos humanos até uma borda e derrube-os com Aard. Acampamentos e o Fosso do Diabo permitem repetir o processo.",
    "environmental": "Aproveite barris, gás, colmeias, quedas e outros elementos do cenário. Comece cedo, pois são necessárias cinquenta mortes.",
    "kaer_morhen_trained": "Isole um inimigo previsível, mantenha a guarda baixa e faça dez contra-ataques seguidos sem bloquear nem sofrer dano.",
    "cant_touch": "Enfrente cinco inimigos fracos, esquive em vez de bloquear e não use Quen até a quinta morte.",
    "evilest_thing": "Cubra o alvo com a bomba Sonho do Dragão e incendeie a nuvem. Repita a interação dez vezes em inimigos resistentes.",
    "mutant": "Suba de nível até abrir todos os espaços e coloque um mutagênico em cada um deles.",
    "butcher": "Agrupe cinco inimigos fracos e mate todos em menos de dez segundos. Bombas e dano em área ajudam.",
    "triple_threat": "Na mesma luta, consiga três mortes com métodos diferentes, por exemplo espada, Sinal e bomba.",
    "brawler": "Avance na sequência de lutas de Skellige e derrote Olaf.",
    "overkill": "Aplique sangramento, veneno e queimadura no mesmo alvo. Virotes de ponta larga, Baforada do Diabo e uma fonte de fogo formam uma combinação segura.",
    "master_marksman": "Enfraqueça humanoides e finalize cinquenta com tiros de besta na cabeça. Mire manualmente e confirme que o último dano veio do virote.",
    "what_was_that": "Contra um único inimigo, ataque, faça um contra-ataque, lance um Sinal e jogue uma bomba dentro de quatro segundos.",
    "even_odds": "Separe dois contratos. Antes do alvo, remova mutagênicos e óleos e não use Sinais, poções ou bombas até a morte ser registrada.",
    "globetrotter": "Descubra cem placas de viagem rápida. A exploração natural das três regiões costuma bastar.",
    "pest_control": "Destrua todos os ninhos de uma única área válida. O guia recomenda Skellige, sem exigir também Velen e Novigrad.",
    "card_collector": "Compre, ganhe e resgate todas as cartas do jogo base. Use a aba Gwent e o Guia Milagroso de Gwent para auditar o que falta.",
    "gwent_master": "Faça um save antes de Grandes Apostas e vença todas as partidas do torneio do Passiflora.",
    "lets_cook": "Compre, encontre ou saqueie doze fórmulas de poções. Herbalistas aceleram o processo.",
    "bombardier": "Adquira fórmulas de seis tipos diferentes de bomba. Confira herbalistas e alquimistas sempre que chegar a uma região nova.",
    "bookworm": "Abra e leia trinta livros, cartas ou documentos. Ler imediatamente após saquear evita perder a contagem.",
    "armed_dangerous": "Complete uma caça ao tesouro de escola de bruxo e equipe ao mesmo tempo as seis peças correspondentes.",
    "power_overwhelming": "Em Pomar Branco, ative um Local de Poder de cada Sinal sem deixar os bônus anteriores expirarem.",
    "brawl_master": "Conclua todas as cadeias de luta de Velen, Novigrad e Skellige.",
    "fast_furious": "Vença todas as corridas, incluindo Vegelbud e o Páreo de Palio. Faça as etapas de Novigrad assim que surgirem.",
    "munchkin": "Chegue ao nível 35. Missões e contratos rendem mais experiência do que limpar inimigos soltos.",
    "fire_hole": "Use bombas para destruir dez ninhos. O progresso conta naturalmente durante Dedetização.",
    "south_star": "Vença uma luta de punhos sem sofrer dano. Use esquivas curtas e contra-ataques contra um adversário inicial.",
    "geralt_friends": "Vença uma rodada usando somente cartas neutras. Faça contra um oponente fraco depois de reunir várias cartas neutras.",
    "all_in": "Jogue três cartas de herói na mesma rodada e depois vença a partida.",
    "shrieker": "Conclua o contrato Berrante (Shrieker) em Velen.",
    "vampire_slayer": "Conclua o contrato ligado aos assassinatos de Byways (The Mystery of the Byways Murders) e derrote Sarasti.",
    "woodland_spirit": "Em No Coração da Floresta, siga a solução de Sven e mate o leshen.",
    "fiend_foe": "Conclua o contrato Filho Desaparecido (Missing Son) em Skellige e derrote Morvudd.",
    "ashes": "Conclua o contrato Batendo Portas (Doors Slamming Shut) em Novigrad e derrote Therazane.",
    "doppler": "Em Ladrão Esquivo (An Elusive Thief), alcance o dúplice durante a perseguição. Se ele fugir, a missão pode falhar. Depois de vencê-lo, matar ou poupar preserva o troféu; volte ao contratante.",
}

assert {item["id"] for item in TROPHIES} == set(TROPHY_TIPS)
