"""Instruções de localização junto aos objetivos, disponíveis offline."""
CONTRACT_STARTS = {
    "jenny_woods": "Quadro de Midcopse.",
    "missing_brother": "Quadro da Estalagem da Encruzilhada (Inn at the Crossroads).",
    "mysterious_tracks": "Quadro de Lindenvale.",
    "patrol_gone_missing": "Quadro do acampamento central nilfgaardiano.",
    "phantom_trade_route": "Refugiados de Benkelham.",
    "shrieker": "Quadro do Poleiro do Corvo (Crow's Perch).",
    "swamp_thing": "Aldeão a oeste do orfanato do Pântano Retorcido.",
    "griffin_highlands": "Poleiro do Corvo, durante a missão de mestre armeiro.",
    "merry_widow": "Quadro de Lindenvale.",
    "byways_murders": "Quadro de Oreton.",
    "woodland_beast": "Quadro do Posto de Fronteira (Border Post).",
    "deadly_delights": "Quadro da Praça do Hierarca (Hierarch Square).",
    "doors_slamming": "Quadro da Praça do Hierarca.",
    "elusive_thief": "Quadro da Praça do Hierarca.",
    "lord_wood": "Quadro da Estalagem do Ganso (Cunny of the Goose).",
    "oxenfurt_drunk": "Quadro do porto de Oxenfurt.",
    "apiarian_phantom": "Quadro de Beanston.",
    "oxenfurt_forest": "Quadro de Oxenfurt.",
    "white_lady": "Quadro ao sul das muralhas de Novigrad.",
    "dragon": "Quadro de Fyresdal.",
    "here_comes_groom": "Quadro de Svorlag.",
    "missing_son": "Quadro de Rannvaig.",
    "muire_dyaeblen": "Quadro do porto de Kaer Trolde.",
    "phantom_eldberg": "Quadro de Arinbjorn.",
    "strange_beast": "Quadro de Larvik.",
}

DETAIL_GUIDES = {
    "white_orchard_power": {
        "title": "Onde ficam os Locais de Poder",
        "visual": "white-orchard-power.svg",
        "map_url": "https://cdn.mos.cms.futurecdn.net/8anNKDBk2QJvzHLafRNdCF.jpg",
        "source": "https://www.pcgamer.com/the-witcher-3-places-of-power-locations/",
        "credit": "Mapa do jogo: CD Projekt Red / PC Gamer",
        "steps": [
            "1. Aard: bosque ao norte do cemitério e do Moinho (Mill), entre pedras grandes.",
            "2. Igni: dentro do cemitério, ao norte da placa do Moinho (Mill). Há uma aparição no local.",
            "3. Axii: atravesse a ponte a oeste do Moinho; procure o bosque a nordeste da Serraria (Sawmill).",
            "4. Quen: colina ao sul da Ponte Quebrada (Broken Bridge). Suba pela trilha depois de cruzar a ponte.",
            "5. Yrden: leste da Vila Abandonada (Abandoned Village), entre árvores ao sul da estrada. Cuidado com o urso.",
            "6. Quen extra: a leste da Ponte Cackler (Cackler Bridge). É outro ponto de habilidade, mas repete o Sinal.",
            "Para o troféu, limpe os inimigos primeiro. Depois faça 1 → 2 → 3 → 4 → 5, absorvendo o poder em cada pedra. Evite meditar ou se distrair: os cinco bônus precisam coexistir. O segundo Quen é opcional para este troféu.",
        ],
    },
    "skellige_nests": {
        "title": "Os cinco ninhos de Skellige",
        "visual": "skellige-nests.svg",
        "steps": [
            "1. Ard Skellig: no naufrágio a oeste/sudoeste de Encruzilhada (Crossroads), perto da praia onde Geralt desembarca.",
            "2. Ard Skellig: siga a costa para sul/sudeste da mesma Encruzilhada. O ninho de afogadores fica ao norte/noroeste de Rannvaig.",
            "3. Ard Skellig: na Estalagem em Ruínas (Ruined Inn), na costa leste.",
            "4. Ard Skellig: Forte Grymmdjarr (Fort Grymmdjarr), a sudoeste de Fyresdal.",
            "5. An Skellig: norte da Baía dos Ventos (Bay of Winds).",
            "Leve bombas próprias para ninhos, como Samum ou Colmeia (Grapeshot). Elimine os guardas, interaja com o ninho e confirme a explosão. Descobrir o ícone não conta como destruí-lo. Estes cinco fecham Dedetização; destrua mais cinco no continente para chegar aos dez do outro troféu.",
        ],
    },
    "witcher_gear_set": {
        "title": "Uma rota concreta: conjunto básico do Grifo",
        "visual": "griffin-gear.svg",
        "steps": [
            "Compre e leia o primeiro mapa de Edwin Greloff no armeiro de Midcopse. Selecione a caça ao tesouro Escola do Grifo (Griffin School Gear) no diário para seguir os marcadores.",
            "Hindhold: procure o andar superior da torre. Ali está o diagrama da espada de aço.",
            "Lornruk: procure o diagrama da espada de prata no complexo do farol. A entrada submersa permite chegar ao interior quando a ponte está levantada.",
            "Gruta do Matador de Dragões (Dragonslayer's Grotto): explore a cripta, derrote a ekimmara e saqueie os quatro diagramas de armadura.",
            "Leve os diagramas e materiais a um armeiro e um ferreiro com nível suficiente. Fabrique armadura, luvas, calças, botas e as duas espadas. Equipe as seis peças juntas quando alcançar o nível exigido. Ter somente os diagramas não basta.",
        ],
    },
}
